name = input("what is your name? ")
color = input("What is your favorite color? ")
age = int(input("how old are you? "))
#print(name "is " + str(age) + "and is a" + color "guy" and  + ".")
print(name)
print("is " + str(age) + " years old")
print("and loves color "+ color + ".")